name: Android Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps
        npx expo install --fix
    
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Prebuild Android
      run: |
        npx expo prebuild --platform android --no-install
    
    - name: Setup Keystore
      run: |
        # 키스토어 파일 생성
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/auto-app-factory.keystore
        
        # 키스토어 파일 확인
        ls -la android/app/auto-app-factory.keystore
        
    - name: Configure Release Signing in build.gradle
      run: |
        # build.gradle 파일 백업
        cp android/app/build.gradle android/app/build.gradle.backup
        
        # Python 스크립트로 build.gradle 수정
        cat > modify_gradle.py << 'PYTHON_EOF'
import re

with open('android/app/build.gradle', 'r') as f:
    content = f.read()

# signingConfigs 추가
if 'signingConfigs {' in content:
    # 기존 signingConfigs에 release 추가
    signing_config = '''
        release {
            storeFile file("auto-app-factory.keystore")
            storePassword "autoappfactory123"
            keyAlias "auto-app-factory"
            keyPassword "autoappfactory123"
        }'''
    
    content = content.replace(
        'signingConfigs {',
        'signingConfigs {' + signing_config
    )
else:
    # signingConfigs 섹션이 없으면 android 블록 안에 추가
    android_pattern = r'(android\s*{)'
    replacement = r'\1\n    signingConfigs {\n        release {\n            storeFile file("auto-app-factory.keystore")\n            storePassword "autoappfactory123"\n            keyAlias "auto-app-factory"\n            keyPassword "autoappfactory123"\n        }\n    }'
    content = re.sub(android_pattern, replacement, content)

# buildTypes의 release에 signingConfig 추가
build_types_pattern = r'(buildTypes\s*{[^}]*release\s*{)'
if re.search(build_types_pattern, content):
    content = re.sub(
        r'(buildTypes\s*{[^}]*release\s*{)',
        r'\1\n            signingConfig signingConfigs.release',
        content
    )

# 파일 저장
with open('android/app/build.gradle', 'w') as f:
    f.write(content)

print("✅ build.gradle modified successfully")
PYTHON_EOF
        
        cd android/app
        python ../../modify_gradle.py
        
        # 수정된 내용 확인
        echo "=== Modified build.gradle ==="
        cat build.gradle | grep -A 20 "signingConfigs" || true
        echo "==="
        cat build.gradle | grep -A 10 "buildTypes" || true
        
    - name: Make Gradlew executable
      run: chmod +x ./android/gradlew
      
    - name: Clean and Build Signed AAB
      working-directory: ./android
      run: |
        # 클린 빌드
        ./gradlew clean
        
        # 릴리스 빌드
        ./gradlew bundleRelease --stacktrace
        
        # 빌드 결과 확인
        echo "=== Build outputs ==="
        ls -la app/build/outputs/bundle/release/
    
    - name: Verify AAB signing
      run: |
        echo "=== Verifying AAB signature ==="
        cd android/app/build/outputs/bundle/release
        
        # jarsigner로 서명 확인
        jarsigner -verify -verbose -certs app-release.aab || echo "Jarsigner verification failed"
        
        # AAB 내용 확인
        echo "=== AAB contents ==="
        unzip -l app-release.aab | head -20
        
        # META-INF 확인
        echo "=== Checking for signatures ==="
        unzip -l app-release.aab | grep "META-INF" || echo "No META-INF found"
        
    - name: Upload AAB to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-bundle
        path: android/app/build/outputs/bundle/release/app-release.aab
        retention-days: 7

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Create Release using GitHub CLI
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        # AAB 파일 경로
        AAB_PATH="android/app/build/outputs/bundle/release/app-release.aab"
        
        # 릴리스 생성
        gh release create "v${{ github.run_number }}" \
          --repo "${{ github.repository }}" \
          --title "Release ${{ github.run_number }} - ${{ steps.date.outputs.date }}" \
          --notes "자동 생성된 릴리스입니다.
        - 릴리스 모드로 서명된 AAB 파일
        - Google Play Console 업로드 가능
        - 빌드 번호: ${{ github.run_number }}
        - 생성 시간: ${{ steps.date.outputs.date }}" \
          "$AAB_PATH#app-release.aab"
        
        echo "✅ Release created successfully!"
