name: Android Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps
        npx expo install --fix
    
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Prebuild Android
      run: |
        npx expo prebuild --platform android --no-install
    
    - name: Setup Keystore and Signing
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/auto-app-factory.keystore
        
        echo "MYAPP_UPLOAD_STORE_FILE=auto-app-factory.keystore" >> android/gradle.properties
        echo "MYAPP_UPLOAD_KEY_ALIAS=auto-app-factory" >> android/gradle.properties
        echo "MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> android/gradle.properties
        echo "MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> android/gradle.properties
        
        cd android/app
        
        echo "" >> build.gradle
        echo "android.signingConfigs {" >> build.gradle
        echo "    release {" >> build.gradle
        echo "        storeFile file('auto-app-factory.keystore')" >> build.gradle
        echo "        storePassword 'autoappfactory123'" >> build.gradle
        echo "        keyAlias 'auto-app-factory'" >> build.gradle
        echo "        keyPassword 'autoappfactory123'" >> build.gradle
        echo "    }" >> build.gradle
        echo "}" >> build.gradle
        echo "" >> build.gradle
        echo "android.buildTypes {" >> build.gradle
        echo "    release {" >> build.gradle
        echo "        signingConfig android.signingConfigs.release" >> build.gradle
        echo "        minifyEnabled false" >> build.gradle
        echo "    }" >> build.gradle
        echo "}" >> build.gradle
        
        echo "=== build.gradle 확인 ==="
        tail -15 build.gradle
        
    - name: Make Gradlew executable
      run: chmod +x ./android/gradlew
      
    - name: Build Signed AAB
      working-directory: ./android
      run: |
        ./gradlew clean
        ./gradlew bundleRelease --stacktrace
        
        echo "=== 빌드 결과 ==="
        ls -la app/build/outputs/bundle/release/
    
    - name: Verify AAB signing
      run: |
        echo "=== AAB 서명 검증 ==="
        cd android/app/build/outputs/bundle/release
        unzip -l app-release.aab | head -20
        echo "=== 서명 파일 확인 ==="
        unzip -l app-release.aab | grep "META-INF" || echo "META-INF 파일 없음"
        
    - name: Upload AAB to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-bundle
        path: android/app/build/outputs/bundle/release/app-release.aab
        retention-days: 7

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Create Release
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        AAB_PATH="android/app/build/outputs/bundle/release/app-release.aab"
        
        gh release create "v${{ github.run_number }}" \
          --repo "${{ github.repository }}" \
          --title "Release ${{ github.run_number }} - ${{ steps.date.outputs.date }}" \
          --notes "릴리스 서명된 AAB 파일 - Google Play Console 업로드 가능" \
          "$AAB_PATH#app-release.aab"
        
        echo "릴리스 생성 완료!"
